print("Enter only two digit number")
a=int(input("enter your number"))
print("The answer will be ",297+a)
b=int(input("again enter your number"))
x=int(99-b)
print("My turn ",x)
c=int(input("again enter your number"))
y=int(99-c)
print("My turn ",y)
d=int(input("again enter your number"))
z=int(99-d)
print("My turn ",z)
m=int(a+b+c+d+x+y+z)
print("The final answer is ",m)
